from tasklist import *
from achievements import *
from task_edit import *
from profile_edit import *
from chat import *
from user_list import *
from user_detail import *
from task_detail import *
from gantt import *
from file_list import *
from project_calendar import *
from user_statistic import *
from project_summary import *
from project_edit import *
from project_graph import *
from project_statistic import *
from life import *
from kanban import *
from taskdrafts import *